apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "wazuh-agent.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "wazuh-agent.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "wazuh-agent.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "wazuh-agent.name" . }}
    spec:
      hostPID: false
      hostNetwork: true
      containers:
        - name: wazuh-agent
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            runAsUser: {{ .Values.securityContext.runAsUser }}
            privileged: {{ .Values.securityContext.privileged }}
          command:
            - /bin/sh
            - '-c'
          args:
            - sed "s|<agent_name>change_me</agent_name>|<agent_name>${WAZUH_AGENT_GROUP}-${NAME}</agent_name>|g" /var/ossec/etc/ossec.conf.tmp > /var/ossec/etc/ossec.conf && /init
          env:
            - name: WAZUH_MANAGER
              value: "{{ .Values.manager.host }}"
            - name: WAZUH_MANAGER_PORT
              value: "{{ .Values.manager.port }}"
            - name: NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: WAZUH_AGENT_GROUP
              value: "{{ .Values.agent.group }}"
          volumeMounts:
            - name: var-run
              mountPath: /var/run
            - name: var-log
              mountPath: /var/log
            - name: wazuh-config
              mountPath: /var/ossec/etc/ossec.conf.tmp
              subPath: ossec.conf
      volumes:
        - name: var-run
          hostPath:
            path: /var/run
        - name: var-log
          hostPath:
            path: /var/log
        - name: wazuh-config
          configMap:
            name: {{ include "wazuh-agent.fullname" . }}-config
      nodeSelector: {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations: {{- toYaml .Values.tolerations | nindent 8 }}
      affinity: {{- toYaml .Values.affinity | nindent 8 }}
